services:
  - type: web
    name: monkpad-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
